import type { Story } from "@/lib/stories";

/**
 * Interactive voice wall — excerpts from Theatre Seed project materials and camp recaps
 */
export const storiesEn: Story[] = [
  {
    id: "1",
    text: "I went from fearing the stage to enjoying it. Theatre gave me confidence. I used to think performing was hard, but after rehearsing again and again, I grew familiar with the whole process—and on opening night I wasn't nervous at all. Focus on each part you're meant to do well, and that is enough.",
    author: "Participant",
    camp: "2025 Winter",
    kind: "student",
  },
  {
    id: "2",
    text: "This place felt like a sanatorium—a year's worth of anxiety was healed here. I still overthink and tense up, but I also became a chatterbox again, with an endless urge to share, because my body knew it could relax here.",
    author: "Participant",
    camp: "2025 Winter",
    kind: "student",
  },
  {
    id: "3",
    text: "When I first arrived in Guangnan, I thought this would simply be performing a play—an outward reflection of life. I didn't expect it to be a journey of finding myself, and an expression and release coming from deep within.",
    author: "Participant",
    camp: "2025 Winter",
    kind: "student",
  },
  {
    id: "4",
    text: "From the first night's conversation, something in me started to melt. I slowed down and observed. When I spoke about someone, it was no longer empty—not abstract, beautiful words, but concrete things. I was so happy! I could express kindness from the heart. Step carefully forward, and be firmly caught. Love to everyone.",
    author: "Participant",
    camp: "2025 Winter",
    kind: "student",
  },
  {
    id: "5",
    text: "Theatre is like life—every detail speaks. Let flowers bloom, let trees be trees, let others be others, and let me return myself whole to myself.",
    author: "Participant",
    camp: "2025 Winter",
    kind: "student",
  },
  {
    id: "6",
    text: "We paid attention to every person in the group, offering the sincerest praise and encouragement. We supported and trusted each other unconditionally. In the quiet of night we talked freely, diluting worry and pain, filling the gaps and confusion inside.",
    author: "Participant",
    camp: "2025 Winter",
    kind: "student",
  },
  {
    id: "7",
    text: "When I came back from university, I said I hoped to receive three hugs this winter. In these few days I feel I've received more than thirty. Not out of politeness—not with my head, but with my body feeling the other person's embrace. These days I've been too happy for words.",
    author: "Participant",
    camp: "2025 Winter",
    kind: "student",
  },
  {
    id: "8",
    text: "Only 19 days into 2025, and I already have the moment I most want to keep from this year.",
    author: "Participant",
    camp: "2025 Winter",
    kind: "student",
  },
  {
    id: "9",
    text: "What moved me most: seven days of uninterrupted rehearsal in Guangnan let us know the space; in that small classroom, deep feeling had already grown, so finishing the performance felt expected. But when we moved to Changsha, we faced all kinds of difficulties… none of them defeated us… everyone was full of energy and passion, encouraging and supporting each other, rehearsing until one or two in the morning. We didn't lose heart! At the final performance, with sound and lighting we hadn't fully rehearsed with, we had so many people supporting us—it was everyone's effort that let us finish strong. The trust between actors and saving each other on stage—that was the strength we gave one another. Together we are strong! Together we can create countless miracles.",
    author: "Participant",
    camp: "2025 Summer",
    kind: "student",
  },
  {
    id: "10",
    text: "After high school I kept telling myself to \"throw myself out there\"—to step to center stage even when I wasn't ready or sure, and still offer my real self to the unknown. This drama camp helped me pick up that belief again. On stage, being \"fully prepared\" is never possible. It is these unusual attempts that break our habits through repeated work together and reveal new possibilities.",
    author: "Participant",
    camp: "2025 Summer",
    kind: "student",
  },
  {
    id: "11",
    text: "Sitting by the river singing—for the first time in my life I sang a song about my own ethnic group, even though I am Dong myself. On a stone by the water, cool stream running between my toes, like moments that quietly slip away… the sweetness and satisfaction flowing through the heart will be etched in each of us. That must be what people mean by \"a life needs only a few moments like these.\"",
    author: "Participant",
    camp: "2025 Summer",
    kind: "student",
  },
  {
    id: "12",
    text: "I used to ask myself: do I really love theatre? Performing The Donkey Gets Water was exhausting, yet I prepared seriously and tried hard to do the role justice… Could the seed of theatre truly sprout in me? I think it has—but slowly, because love has a cost. I can bear the hardship of loving something, and I'm willing to give energy and heart to theatre—so yes, I love it.",
    author: "Participant",
    camp: "2025 Summer",
    kind: "student",
  },
  {
    id: "13",
    text: "Most memorable: the field exploration on the first evening, when strangers warmed to each other quickly through helping one another! At first some people weren't used to grass brushing their skin; then we walked the fields together, singing \"Rice Fragrance,\" with lights, photos, and video—it was pure happiness.",
    author: "Participant",
    camp: "2025 Summer",
    kind: "student",
  },
  {
    id: "14",
    text: "After rehearsing all day in the summer heat, our evening activity was by the stream that runs through Guangnan Village. With the murmuring water and the sunset, our script read-aloud felt deeply beautiful—as if the script gained more soul.",
    author: "Participant",
    camp: "2025 Summer",
    kind: "student",
  },
  {
    id: "15",
    text: "On the last day we encouraged each other. Even facing a sea of people and feeling very nervous, my partners' hugs and old friends in the audience gave me enormous security. Hand in hand at the curtain call—that feeling of finishing a whole play was exhilarating.",
    author: "Participant",
    camp: "2025 Summer",
    kind: "student",
  },
  {
    id: "16",
    text: "First I saw the diversity and possibility of life—everyone comes from different places with different lives. Spending time together, I saw many different paths. Suddenly a lot of things didn't feel worth fixating on. The world is wide; we can choose whatever we love to do, without having to stay in any narrow corner.",
    author: "Participant",
    camp: "2025 Summer",
    kind: "student",
  },
  {
    id: "17",
    text: "My favorite part of this winter camp was script creation. I remember our group in a teahouse private room—dim light, Guagua playing hospital ambience on a laptop, everyone silent or sitting or walking around, thoughts drifting in the calm. What stayed with me most was when we sat together and shared ideas—I saw everyone's wild imagination and quick wit.",
    author: "Participant",
    camp: "2026 Winter",
    kind: "student",
  },
  {
    id: "18",
    text: "The moment that stays with me most is when we all wrote on the calendar together in the inn lobby and hotel rooms—after the performance we debriefed again and looked back at those moments. What I felt most was my partners' companionship. Imperfection happened, and we believed what happened was for the best—a feeling of being accepted.",
    author: "Participant",
    camp: "2026 Winter",
    kind: "student",
  },
  {
    id: "19",
    text: "I gained friendship! Everyone is such good people—those moving moments of truly seeing each other will stay with me a long time. Improvisation can be part of life; facing the unknown with an improviser's attitude gave me a little more courage.",
    author: "Participant",
    camp: "2026 Winter",
    kind: "student",
  },
  {
    id: "20",
    text: "What changed for me: I have confidence in communal living again, and I saw how good people can be! I haven't been this happy in a long time.",
    author: "Participant",
    camp: "2026 Winter",
    kind: "student",
  },
  {
    id: "21",
    text: "My biggest takeaway is that I really tried and experienced theatre, got wonderful feedback, and later at Winter Traveller heard that some partners were inspired by our work and wanted to use drama to show their own results—I could even offer some advice.",
    author: "Participant",
    camp: "2026 Winter",
    kind: "student",
  },
  {
    id: "22",
    text: "Creative activities and daily debriefs felt new to me—everyone's imagination is huge, and it's fascinating. I didn't used to like daily debriefs because I had to speak in front of many people, but I grew to love them. They feel like moments when we can truly resonate—and you discover so many new things.",
    author: "Participant",
    camp: "2026 Winter",
    kind: "student",
  },
];
